// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cjmNrqiWKvSNnENbXRiH5O-EZqodGaQ',
    appId: '1:93523399209:web:c77ab5de97d401170d4238',
    messagingSenderId: '93523399209',
    projectId: 'olxapp-c5e5c',
    authDomain: 'olxapp-c5e5c.firebaseapp.com',
    storageBucket: 'olxapp-c5e5c.appspot.com',
    measurementId: 'G-89X3MVR2X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7L9Etsz1LseGrjST6VsTDwKjfX5oVpVI',
    appId: '1:93523399209:android:28d47d6aa5975e5d0d4238',
    messagingSenderId: '93523399209',
    projectId: 'olxapp-c5e5c',
    storageBucket: 'olxapp-c5e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgDY9EEjUk6eeqVDRQmC42GCIf1IqxQjI',
    appId: '1:93523399209:ios:b17d51518fe797a60d4238',
    messagingSenderId: '93523399209',
    projectId: 'olxapp-c5e5c',
    storageBucket: 'olxapp-c5e5c.appspot.com',
    iosClientId: '93523399209-k7os8cs7fo8j5ck99nt1vbc38j9u3o1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgDY9EEjUk6eeqVDRQmC42GCIf1IqxQjI',
    appId: '1:93523399209:ios:05fe55f9e8630e8a0d4238',
    messagingSenderId: '93523399209',
    projectId: 'olxapp-c5e5c',
    storageBucket: 'olxapp-c5e5c.appspot.com',
    iosClientId: '93523399209-qhm3afd0qnu4vs709neg4j531cgirhvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxAppFirebase.RunnerTests',
  );
}
